apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure/namespaces/
  - infrastructure/openbao/
  - apps/

patches:
  - path: bases/namespace/common-labels.yaml
    target:
      kind: Namespace
