apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo.yaml
  - messaging.yaml
  - openbao.yaml
  - istio-system.yaml
  - ci-rbac.yaml

patches:
  - path: patches/common-labels.yaml
    target:
      kind: Namespace
