apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - headlamp.yaml
  - headlamp-admin.yaml
  - networkpolicy.yaml
  - default-deny-ingress.yaml

images:
  - name: ghcr.io/headlamp-k8s/headlamp
    newTag: "v0.30.0"
