apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openbao-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: demo
    ports:
    - protocol: TCP
      port: 8200
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 8200
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tailscale
    ports:
    - protocol: TCP
      port: 8200
