apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo/
  - rabbitmq/
  - headlamp/
  - openbao/

patches:
  - path: _patches/security-context/pod-security-context.yaml
    target:
      kind: Deployment
  - path: _patches/security-context/container-security-context.json
    target:
      kind: Deployment
