apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

resources:
  - namespace.yaml
  - sample-app/deployment.yaml
  - sample-app/service.yaml
  - networkpolicy.yaml
  - default-deny-ingress.yaml
